spring:
  config:
    import: optional:file:.env[.properties]

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DBURL}
    username: ${DBUSER}
    password: ${DBPW}

  jpa:
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always

logging.level:
  org.hibernate.sql: debug

map:
  id: ${MAPID}

csv-path: /toilet.csv